import { Router } from 'express';
import { authRouter } from '../modules/auth/auth.routes';
import { usersRouter } from '../modules/users/users.routes';
import { clientsRouter } from '../modules/clients/clients.routes';
import { vehiclesRouter } from '../modules/vehicles/vehicles.routes';
import { entriesRouter } from '../modules/entries/entries.routes';
import { entryPhotosRouter, photosRouter } from '../modules/photos/photos.routes';
import { entryDamagesRouter, damagesRouter } from '../modules/damages/damages.routes';
import { entryLaborRouter, laborRouter } from '../modules/labor/labor.routes';
import { entryPartsRouter, partsRouter } from '../modules/parts/parts.routes';
import { entryCostsRouter, costsRouter } from '../modules/costs/costs.routes';
import { entryStagesRouter, stagesRouter } from '../modules/repairs/repairs.routes';
import { entryInvoiceRouter, invoicesRouter } from '../modules/invoices/invoices.routes';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes';
import { financeRouter } from '../modules/finance/finance.routes';
import { entryNotificationsRouter, staffNotificationsRouter } from '../modules/notifications/notifications.routes';
import { clientPortalRouter } from '../modules/clientPortal/clientPortal.routes';
import { clientAuthRouter } from '../modules/clientAuth/clientAuth.routes';
import { clientFleetRouter } from '../modules/clientFleet/clientFleet.routes';
import { entryWorkRequestsRouter, workRequestsRouter } from '../modules/workRequests/workRequests.routes';
import { inventoryRouter } from '../modules/inventory/inventory.routes';
import { materialRequestsRouter } from '../modules/materialRequests/materialRequests.routes';
import { remindersRouter } from '../modules/reminders/reminders.routes';
import { reportsRouter } from '../modules/reports/reports.routes';
import { deviceTokensRouter } from '../modules/deviceTokens/deviceTokens.routes';

// Central mount point for every feature module's router.
export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/clients', clientsRouter);
apiRouter.use('/vehicles', vehiclesRouter);
// More specific paths registered before the generic "/entries" mount so they
// match first instead of falling through entriesRouter's own routing.
apiRouter.use('/entries/:entryId/photos', entryPhotosRouter);
apiRouter.use('/entries/:entryId/damages', entryDamagesRouter);
apiRouter.use('/entries/:entryId/labor', entryLaborRouter);
apiRouter.use('/entries/:entryId/parts', entryPartsRouter);
apiRouter.use('/entries/:entryId/costs', entryCostsRouter);
apiRouter.use('/entries/:entryId/stages', entryStagesRouter);
apiRouter.use('/entries/:entryId/invoice', entryInvoiceRouter);
apiRouter.use('/entries/:entryId/notifications', entryNotificationsRouter);
apiRouter.use('/entries/:entryId/work-requests', entryWorkRequestsRouter);
apiRouter.use('/entries', entriesRouter);
apiRouter.use('/photos', photosRouter);
apiRouter.use('/damages', damagesRouter);
apiRouter.use('/labor', laborRouter);
apiRouter.use('/parts', partsRouter);
apiRouter.use('/costs', costsRouter);
apiRouter.use('/stages', stagesRouter);
apiRouter.use('/invoices', invoicesRouter);
apiRouter.use('/work-requests', workRequestsRouter);
apiRouter.use('/inventory-items', inventoryRouter);
apiRouter.use('/material-requests', materialRequestsRouter);
apiRouter.use('/notifications', staffNotificationsRouter);
apiRouter.use('/reminders', remindersRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/device-tokens', deviceTokensRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/finance', financeRouter);
apiRouter.use('/client/:token', clientPortalRouter);
apiRouter.use('/client-auth', clientAuthRouter);
apiRouter.use('/client-fleet', clientFleetRouter);
